### ISSUE TITLE
banking app detects root or something like that wenn RIRU Core Magisk Module is installed

### ISSUE THREAD

**Issue by mcdoubleyou** [Magisk-Modules-Repo/riru-core#1] opened 2019-11-08 14:51 UTC
Hello folks,

my banking app doesn't work if the RIRU Core Magisk Module is installed.
For all other Magisk Modules hide works as designed.

Any idea whats wrong or is this a known bug?

If RIRU Core isn't installed the app will start with info that maybe root is active and I shouldn't use it, but I could.

In case you need more details pls provide information so a noob could do it.
Even I'm an IT administrator my knowledge about Android is very limited.

Thanks!
mcdy

**Comment by upthekhyber** [comment] 2020-03-30 15:58
I am experiencing the same issue, were you able to resolve this?

**Comment by adriantc** [comment] 2020-11-01 20:24
I can confirm this issue is still happening with the latest version of Core (21.3). My banking application (https://play.google.com/store/apps/details?id=ro.ing.mobile.banking.android.activity&hl=en) detects it when it is enabled. I can confirm Magisk Hide is enabled and app hidden, Magisk is repackaged and the app is Blacklisted in EdXposed.

**Comment by RikkaW** [comment] 2020-11-02 05:23
Close this issue because:
1. This is a Magisk module repo. Riru repo is https://github.com/RikkaApps/Riru.
2. Riru v22 has done a lot to prevent being detected from multiple methods

**Closed by RikkaW** 2020-11-02 05:23 UTC
